//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleCom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticleCom()
        {
            this.ArticleReply = new HashSet<ArticleReply>();
        }
    
        public int ArticleComID { get; set; }
        public int ArticleID { get; set; }
        public string ComContent { get; set; }
        public System.DateTime ComTime { get; set; }
        public int UserID { get; set; }
    
        public virtual Articles Articles { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleReply> ArticleReply { get; set; }
    }
}
