//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food()
        {
            this.Collect = new HashSet<Collect>();
            this.FoodCom = new HashSet<FoodCom>();
        }
    
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public string FoodImage { get; set; }
        public string FoodVideo { get; set; }
        public string Notice { get; set; }
        public string Setp1 { get; set; }
        public string Image1 { get; set; }
        public string Step2 { get; set; }
        public string Image2 { get; set; }
        public string Step3 { get; set; }
        public string Image3 { get; set; }
        public Nullable<int> FoodCategoryID { get; set; }
        public Nullable<int> TagID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string yuanliao { get; set; }
        public Nullable<System.DateTime> CTime { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<int> SpecialID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collect> Collect { get; set; }
        public virtual FoodCategory FoodCategory { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual Special Special { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodCom> FoodCom { get; set; }
    }
}
