//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FoodUsers
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public string FoodImage { get; set; }
        public string FoodVideo { get; set; }
        public string Notice { get; set; }
        public string Setp1 { get; set; }
        public string Image1 { get; set; }
        public string Step2 { get; set; }
        public string Image2 { get; set; }
        public string Step3 { get; set; }
        public string Image3 { get; set; }
        public Nullable<int> FoodCategoryID { get; set; }
        public Nullable<int> TagID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string yuanliao { get; set; }
        public Nullable<System.DateTime> CTime { get; set; }
        public Nullable<int> MenuID { get; set; }
        public Nullable<int> SpecialID { get; set; }
        public string UserName { get; set; }
        public string HeadPic { get; set; }
        public string Description { get; set; }
    }
}
