//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_SpecialFood
    {
        public int FoodID { get; set; }
        public string FoodName { get; set; }
        public string FoodImage { get; set; }
        public string UserName { get; set; }
        public string HeadPic { get; set; }
        public int SpecialID { get; set; }
        public string SpecialName { get; set; }
        public string SpecialJS { get; set; }
        public string SpecialImage { get; set; }
    }
}
