//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ArticleUsers
    {
        public int ArticleID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> ComAID { get; set; }
        public Nullable<int> ArticleCategoryID { get; set; }
        public string Picture { get; set; }
        public string HeadLine { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public string HeadPic { get; set; }
        public string ArticleCategory { get; set; }
    }
}
